USE [master]
GO

/****** Object:  Database [Hallo]    Script Date: 28/08/2017 09:49:09 p.m. ******/
CREATE DATABASE [Hallo]
GO

ALTER DATABASE [Hallo] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hallo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hallo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hallo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hallo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hallo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hallo] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hallo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hallo] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Hallo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hallo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hallo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hallo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hallo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hallo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hallo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hallo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hallo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hallo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hallo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hallo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hallo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hallo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hallo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

